"""Reader-facing Chinese explanations; original configuration identifiers stay intact."""
import re

TABLE_LABELS = {
 'AIPropInfoConfig':'AI 神器配置',
 'ArenaEnemyBalanceInfogameplay_improve_01':'竞技场敌方平衡配置·玩法优化 01 版',
 'BaseConfigConfig':'骰子冒险基础配置',
 'BuildConfigConfig':'骰子冒险建筑与格子事件配置',
 'CheckInRewardsConfig':'签到奖励配置',
 'CheckInRewardsIndexConfig':'签到奖励组索引',
 'ChessboardConfig':'骰子冒险棋盘配置',
 'CumulativeRewardConfig':'累计签到奖励配置',
 'DailyTaskConfig':'骰子冒险每日任务配置',
 'EnemyDifficultLevelInfosgameplay_improve_01':'敌方难度等级信息·玩法优化 01 版',
 'FundIAPInfo':'基金内购与奖励档位信息',
 'GameSettingConfig':'游戏通用规则配置',
 'GlobaMultistageNewcomerPackageInfo':'分阶段新手礼包信息',
 'GlobaUpgradeReward':'账号升级奖励配置',
 'GlobalArchitectureInfogameplay_improve_01':'全局建筑信息·玩法优化 01 版',
 'GlobalArenaInfoSheet2':'全局竞技场信息·Sheet2 表',
 'GlobalArtifactAIReleaseInfo':'神器 AI 释放条件信息',
 'GlobalArtifactsForgeInfo':'神器重铸词条信息',
 'GlobalBaseAssetsInfo':'全局基础资源信息',
 'GlobalBlessInfo':'全局祝福信息',
 'GlobalBoxInfo':'全局宝箱信息',
 'GlobalCardTalent2Info':'卡牌与新技能对应信息',
 'GlobalCardTalentInfoSheet3':'卡牌技能效果信息·Sheet3 表',
 'GlobalDanInfoSheet2':'全局奖杯段位信息·Sheet2 表',
 'GlobalExpression':'全局表情配置',
 'GlobalFeatureUnlockInfo':'全局功能解锁信息',
 'GlobalFormulasInfo':'全局数值公式信息',
 'GlobalFundInfoAbilityFund':'技能基金奖励信息',
 'GlobalFundInfoCardFund':'卡牌基金奖励信息',
 'GlobalFundInfoMainCityPass':'领地通行证奖励信息',
 'GlobalFundInfoSeasonPass':'旧赛季通行证奖励信息',
 'GlobalFundInfoSummonFund':'召唤基金奖励信息',
 'GlobalGiftChainInfo':'链式礼包信息',
 'GlobalGiftChainInfo2':'第二套链式礼包信息',
 'GlobalHeroCardInfoSheet5':'全局英雄卡牌信息·Sheet5 表',
 'GlobalHexInfo':'全局六边形地块信息',
 'GlobalMainCityAssetsInfo':'领地建筑美术资源信息',
 'GlobalMainCityBuildTalentInfoSheet2':'领地建筑属性加成信息·Sheet2 表',
 'GlobalMainCityHouseInfo':'领地家族信息',
 'GlobalMainCityMapInfo':'领地地图信息',
 'GlobalMainCityTitleInfo':'领地称号与基础收益信息',
 'GlobalMysteriousStore':'全局神秘商店信息',
 'GlobalPolygonArenaInfoSheet2':'多边形竞技场地图信息·Sheet2 表',
 'GlobalPropInfoBTest':'全局神器信息·B 测试表',
 'GlobalRandomHeroCardInfo':'随机英雄卡牌奖励信息',
 'GlobalRoleInfogameplay_improve_01':'全局战斗单位信息·玩法优化 01 版',
 'GlobalShopInfo':'全局商店信息',
 'GlobalSummonInfo':'全局神器召唤信息',
 'GlobalTalentFormulasInfoSheet2':'领主塔属性成长公式·Sheet2 表',
 'GlobalTrophyProgressInfo':'奖杯进度与节点奖励信息',
 'GlobalTutorialInfo':'全局教程流程信息',
 'GlobalTrainingMapInfoSheet2':'训练地图与教程奖励信息·Sheet2 表',
 'GlobalUpgradeTalentPriceInfoabilities_in_advance':'额外技能解锁等级与升级价格信息·提前开放分支',
 'GlobalWeeklyCardDailyTaskInfo':'每周主题卡每日任务信息',
 'GlobalWeeklyCardStageInfo':'每周主题卡阶段奖励信息',
 'How2PlayConfig':'骰子冒险玩法说明配置',
 'I2Terms':'本地化文本词条',
 'LapsConfigConfig':'骰子冒险跑圈成长配置',
 'LimitedPropInfoConfig':'限定神器召唤奖励池配置',
 'LimitedPropOrderConfig':'限定神器轮换顺序配置',
 'LimitedPropPackConfig':'限定神器召唤礼包配置',
 'PoolConfigConfig':'骰子冒险奖励池配置',
 'PremiumCustomGiftPackConfig':'尊享自选礼包配置',
 'PremiumGiftPackConfig':'尊享礼包配置',
 'PropAttrBuffInfoConfig':'神器被动属性关联配置',
 'PropAttrEnumInfoConfig':'神器属性成长与上限配置',
 'PropAttrTypeConfig':'神器属性类型与换算系数配置',
 'PropRankUpInfoConfig':'神器升星升阶配置',
 'PropUpgradeInfoConfig':'神器等级升级配置',
 'PvpBotConfig':'PVP 机器人预设配置',
 'PvpMapConfig':'PVP 地图池配置',
 'PvpMatchingConfig':'PVP 匹配窗口配置',
 'PvpPropPieceConfig':'PVP 神器碎片奖励权重配置',
 'PvpRankConfig':'PVP 段位规则配置',
 'PvpRankingListConfig':'PVP 排行榜奖励配置',
 'PvpSeasonPassConfig':'PVP 赛季通行证模板配置',
 'PvpSeasonPassRewardConfig':'PVP 赛季通行证奖励配置',
 'PvpSeasonTaskConfig':'PVP 赛季任务配置',
 'PvpSettingConfig':'PVP 全局规则配置',
 'PvpStateConfig':'PVP 强敌分差与额外积分配置',
 'RuinsConfigConfig':'骰子冒险遗迹事件配置',
 'S2Rank2PlayConfig':'S2 冲榜活动规则说明',
 'S2RankRewardListConfig':'S2 冲榜名次奖励配置',
 'S2RushRewardsConfig':'S2 冲榜活动奖品配置',
 'SeasonRankingRewardConfigSheet2':'赛季排行榜奖励配置·Sheet2 表',
 'ShopArenaPackInfos':'竞技场商店礼包信息',
 'SummerCarnival2PlayConfig':'夏日嘉年华玩法说明',
 'SummerCarnivalCheckConfig':'夏日嘉年华签到配置',
 'SummerCarnivaldailyTaskConfig':'夏日嘉年华每日任务配置',
 'SummerCarnivalpointShopConfig':'夏日嘉年华积分商店配置',
 'TotalDiceConfig':'累计消耗骰子奖励配置',
 'UserLablePushPackInfo':'用户标签关联推送礼包信息',
 'UserLevelInfo':'账号等级经验信息',
 'VideoBtnConfig':'激励视频按钮与入口配置',
 'WeeklyCardPoolConfig':'每周主题卡卡池配置',
 'WeeklyCardUIConfig':'每周主题卡界面资源配置',
 'WeeklyClashDifficultyConfigSheet2':'周锦标赛难度与积分配置·Sheet2 表',
 'WordEmojiConfig':'文字表情配置',
 'RemoteConfig':'远程配置缓存',
}

# Switch names establish a likely branch, not its complete runtime behavior.
SWITCHES = {
 'NewAbilitySystem':('新卡牌技能系统开关','推测：选择新版额外技能流程；结合技能对应表与教程判断。'),
 'AbilityTreeSystem':('天赋树系统开关','推测：控制旧天赋树分支的启用。'),
 'NewArtifactsPlay':('新版神器玩法开关','推测：选择翻格充能等新版神器玩法；不据此保证所有旧冷却逻辑都被移除。'),
 'ArtifactsSystem':('神器系统开关','推测：控制神器相关功能是否启用。'),
 'NewMainCity2':('新版领地第二套方案开关','推测：选择领地探索玩法的第二套分支，具体覆盖范围未还原。'),
 'NewMainCitySystem':('新版领地系统开关','推测：控制另一套领地改版分支；值为 0 不代表整个领地功能关闭。'),
 'NewArenaProcess':('新版竞技场进度流程开关','推测：选择新版竞技场推进与解锁流程。'),
 'NoBet':('免下注模式开关','推测：使用无需下注的竞技场流程。'),
 'ArenaDifficultyV2':('竞技场难度第二版开关','推测：切换第二版对手难度规则。'),
 'NewArenaMap':('新版竞技场地图开关','推测：选择新版地图池或布局分支。'),
 'MinesCountLimit':('金矿数量限制开关','推测：应用竞技场中的金矿数量上限。'),
 'UnitsCountLimit':('单位数量限制开关','推测：控制某套单位数量上限逻辑；值为 0 不证明所有模式均无上限。'),
 'Season':('赛季系统开关','推测：控制赛季相关入口或规则分支。'),
 'WeeklyCardEvent':('每周主题卡活动开关','推测：控制主题卡轮换活动是否启用。'),
 'DailyBless':('每日祝福开关','推测：控制每日祝福入口或效果流程。'),
 'NewMoraleSystem':('新版士气系统开关','推测：选择新版士气分支；值为 0 不足以证明旧士气系统也关闭。'),
 'UserSegmentation':('用户分群开关','推测：启用用户分类逻辑；具体使用哪些标签、是否影响匹配未确认。'),
 'DynamicDifficulty01':('动态难度方案 01 开关','推测：控制一套动态难度调整分支；具体调节指标未确认。'),
 'BalanceAdjustment02':('平衡调整方案 02 开关','推测：选择第二套平衡修正；涉及哪些卡牌、羁绊或数值未确认。'),
 'BalanceAdjustment03':('平衡调整方案 03 开关','推测：选择第三套平衡修正；不能按编号推断它必然取代其他方案。'),
}

FIELD_LABELS = {
 'victoryGoldNoBet':'免下注分支的胜利金币',
 'dailyGoldLimitNoBet':'免下注分支的金币日上限',
 'trophyReward':'胜利奖杯增量',
 'trophyPunish':'失败奖杯扣减基数',
 'NormalPVPWinExp':'普通对战胜利账号经验',
 'NormalPVPLoseExp':'普通对战失败账号经验',
 'SeasonPVPWinExp':'赛季对战胜利账号经验',
 'SeasonPVPLoseExp':'赛季对战失败账号经验',
 'chestRange':'推测：胜利宝箱抽取范围配置',
 'boxRewardFold':'推测：宝箱奖励倍率，作用范围待确认',
 'S_Base_Win':'PVP 胜利基础积分',
 'S_Base_Lose':'PVP 失败扣分基数',
 'S_Bonus_Strong':'推测：战胜较强对手的额外积分',
 'S_Bonus_Streak':'推测：连胜额外积分',
 'PvpPass_WinScore':'PVP 胜利通行证经验奖励',
 'PvpPass_LoseScore':'PVP 失败通行证经验奖励',
 'FixedReward':'固定物品奖励配置',
 'RandomReward1':'第一组随机奖励配置',
 'RandomReward2':'第二组随机奖励配置',
 'RewardShow':'奖励展示配置',
 'Reward_Win':'推测：胜利奖励次数或门槛参数，具体含义未确认',
 'Like_Reward':'推测：点赞行为奖励',
 'DailySPPointsMatches':'旧通行证每日计入对战次数参数',
 'NormalPVPWinSeasonPassExp':'普通对战胜利的旧通行证经验参数',
 'SuccessPanel_NoEmptySpace':'胜利结算文本·没有空位',
 'SteerTutorialContent_12002':'引导教程文本·战斗胜利宝箱',
 'MonthlyCardPanel_DesMoreReward':'月卡文本·胜利奖励提升 20%',
 'SteerTutorialContent_5002':'引导教程文本·胜负士气变化',
 'CanUse':'本地启用标记',
 'attack':'攻击字段；金矿表中表示每次金币产量',
 'coolDown':'冷却时间字段；新版是否沿用待确认',
 'buildType':'建筑加成类别',
 'maxRewardMins':'挂机奖励最多累计分钟数',
 'hexLevel':'推测：称号对应的地块探索进度门槛',
 'hexPrice':'推测：对应称号档位的翻格费用',
 'NeedRank':'升级所需升阶条件',
 'Rank':'阶数；与累计升阶口径需区分',
 'Star':'星级',
 'Level':'等级字段；在词条表中推测为解锁等级要求',
 'Weight':'奖励权重；是否用于实际抽取待确认',
 'ShowWeight':'推测：展示用奖励权重',
 'Item':'奖励类别枚举；具体映射待确认',
 'Factor':'属性换算系数',
 'randomFromOwnedCards':'是否从已拥有卡牌中随机抽取',
 'completeTrophyRequire':'竞技场完成进度所需奖杯字段',
 'winCountUnLock':'推测：按胜场数解锁的旧条件',
 'Pvp_OpenMainLevel':'PVP 开放所需竞技场等级',
 'Season_Time':'推测：赛季持续天数',
 'Pvp_BotTime':'推测：机器人补位等待时间参数',
 'Pvp_BotProb':'推测：机器人补位概率参数',
 'recover_interval_hour':'骰子自然恢复间隔；本表数值按秒解释',
 'Rookie':'推测：新手用户标签',
 'Expert':'推测：熟练用户标签',
 'LosingStreak':'推测：连败用户标签',
 'JustPaidUser':'推测：近期付费用户标签',
 'DefaultValue':'默认值来源',
 'ConfigurationRule':'配置规则来源',
 'type':'规则类型枚举',
 'args':'规则参数',
 '_B':'B 分支文本后缀；不等于已确认当前启用',
 'HeroCardPanel_*FettersBuff':'卡牌面板各类羁绊效果文本',
 'SteerTutorialContent_1001':'引导教程文本·领主塔产金币',
 'SteerTutorialContent_20000':'引导教程文本·神器翻格充能',
 'SteerTutorialContent_6001':'引导教程文本·领地开放',
 'systems-evidence.json':'系统分析证据索引文件',
}
LABELS={**TABLE_LABELS,**{k:v[0] for k,v in SWITCHES.items()},**FIELD_LABELS}

def display_label(name):
 return name+'（'+LABELS[name]+'）' if name in LABELS else name

def annotate_markdown(text):
 """Annotate code references and bare table cells without changing original IDs."""
 parts=re.split(r'(`[^`\n]+`)',text)
 bare_names=sorted([k for k in LABELS if k not in ['systems-evidence.json','HeroCardPanel_*FettersBuff']],key=len,reverse=True)
 bare=re.compile(r'(?<![\w])('+'|'.join(re.escape(k) for k in bare_names)+r')(?![\w])')
 for i,part in enumerate(parts):
  if part.startswith('`'):
   raw=part[1:-1]
   if raw in LABELS:parts[i]=part+'（'+LABELS[raw]+'）';continue
   if re.fullmatch(r'[A-Za-z][A-Za-z0-9_]+#\d+',raw):
    base,idx=raw.split('#')
    if base in LABELS:parts[i]=part+'（'+LABELS[base]+'，记录 '+idx+'）'
   elif '=' in raw:
    bases=re.findall(r'([A-Za-z][A-Za-z0-9_]*)\s*=',raw)
    if bases and all(k in LABELS for k in bases):parts[i]=part+'（'+'；'.join(LABELS[k] for k in bases)+'）'
  else:
   parts[i]=bare.sub(lambda m:'`'+m[0]+'`（'+LABELS[m[0]]+'）',part)
 return ''.join(parts)
