const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async()=>{
  const out=path.resolve(__dirname,'../outputs/battle-rules');
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  const errors=[];
  try{
    const page=await browser.newPage({viewport:{width:1360,height:900}});
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(pathToFileURL(path.join(out,'index.html')).href);
    assert.equal(await page.locator('article h2').count(),3);
    assert.equal(await page.locator('article h3').count(),24);
    assert.equal(await page.locator('#module-overview').innerText(),'模块一：局内整体流程规则');
    assert.equal(await page.locator('#module-hex').innerText(),'模块二：地图与翻格子规则');
    assert.match(await page.locator('#hex-3').innerText(),/190条记录/);
    assert.match(await page.locator('#hex-4').innerText(),/逐档扩池/);
    assert.match(await page.locator('article').innerText(),/22种几何布局签名/);
    assert.match(await page.locator('article').innerText(),/累计消耗2000金币必出金卡/);
    assert.match(await page.locator('#hex-8').innerText(),/具体卡牌/);
    assert.match(await page.locator('article').innerText(),/TryApplyFirstThreeCheapOpenReroll/);
    assert.match(await page.locator('article').innerText(),/对剩余候选按列表索引均匀抽取/);
    assert.match(await page.locator('article').innerText(),/func\[15972\]/);
    assert.match(await page.locator('article').innerText(),/拒绝采样/);
    assert.match(await page.locator('article').innerText(),/价格\s*低于250/);
    assert.match(await page.locator('article').innerText(),/刚付费[\s\S]*连败[\s\S]*回流[\s\S]*连胜/);
    assert.equal(await page.locator('#arenaSelect option').count(),20);
    await page.locator('#arenaSelect').selectOption('19');
    assert.equal(await page.locator('[data-arena="countDownTime"]').innerText(),'300');
    assert.equal(await page.locator('[data-arena="victoryGoldNoBet"]').innerText(),'800');
    const id=page.locator('.idtip',{hasText:'1007'}).first();
    await id.hover();
    assert.equal(await page.locator('#tooltip').isVisible(),true);
    assert.match(await page.locator('#tooltip').innerText(),/摧毁敌人的所有建筑/);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#tooltip').isVisible(),false);
    await page.screenshot({path:path.join(out,'battle-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:path.join(out,'battle-mobile.png'),fullPage:false});
    assert.deepEqual(errors,[]);
  }finally{await browser.close()}
  const file=path.join(out,'verification.json'),verification=JSON.parse(fs.readFileSync(file,'utf8'));
  verification.uiQA={passed:true,checks:['2大内容模块+证据附录','24个分节目录','20档竞技场切换','190条多边形记录分析','132条PVP地图候选分析','具体卡牌候选链','WASM等概率抽取函数','前三次低价重抽阈值与候选池','账号标签概率加成','概率修改器与保底','ID悬浮说明','Escape关闭','390px响应式'],pageErrors:errors};
  fs.writeFileSync(file,JSON.stringify(verification,null,2));
  console.log(JSON.stringify(verification.uiQA));
})().catch(e=>{console.error(e);process.exitCode=1});
