const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  try {
    const page=await browser.newPage({viewport:{width:1360,height:900}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(pathToFileURL(path.resolve(__dirname,'../docs/reports/chests/index.html')).href);
    assert.equal(await page.locator('#arena option').count(),20);
    assert.equal(await page.locator('details').count(),8);
    await page.locator('#arena').selectOption('6');
    const king=page.locator('#arena-result tr').filter({hasText:'国王宝箱'});
    assert.match(await king.innerText(),/150分钟/);
    assert.match(await king.innerText(),/90 \/ 45 \/ 24/);
    assert.match(await king.innerText(),/120 \/ 120 \/ 30/);
    await page.locator('#arena').selectOption('7');
    assert.match(await king.innerText(),/160分钟/);
    assert.match(await king.innerText(),/120 \/ 120 \/ 30/);
    await page.locator('#arena').selectOption('19');
    assert.equal(await page.locator('#arena-result tbody tr').count(),2);
    assert.match(await page.locator('#arena-result').innerText(),/传奇宝箱/);
    await page.locator('#branch').selectOption('1');
    assert.doesNotMatch(await page.locator('#arena-result').innerText(),/传奇宝箱/);
    assert.match(await page.locator('#arena-result').innerText(),/国王宝箱/);
    const firstTip=page.locator('[data-tip]').first();
    await firstTip.focus();
    assert.equal(await page.locator('#tooltip').isVisible(),true);
    assert.match(await page.locator('#tooltip').innerText(),/WoodChest/);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#tooltip').isVisible(),false);
    await page.locator('details summary').first().click();
    assert.equal(await page.locator('details').first().getAttribute('open'),'');
    await page.locator('details summary').first().click();
    await page.evaluate(()=>scrollTo(0,0));
    await page.screenshot({path:path.resolve(__dirname,'../outputs/chests/desktop.png')});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:path.resolve(__dirname,'../outputs/chests/mobile.png')});
    assert.deepEqual(errors,[]);
    console.log('PASS: arena 7/8 time and reward comparison, arena 20 branch pools, tooltip keyboard access, source expand/collapse, mobile overflow, browser script errors');
  }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
